version: '3'

services:

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: book_store

